# Generated by Django 3.2.6 on 2021-08-13 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado_em', models.DateTimeField(auto_created=True)),
                ('atualizaocao', models.DateTimeField(auto_now=True)),
                ('name_com', models.CharField(max_length=255, unique=True)),
                ('num_parks', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Complexo',
                'verbose_name_plural': 'Complexos',
                'db_table': 'comp_table',
            },
        ),
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado_em', models.DateTimeField(auto_created=True)),
                ('atualizaocao', models.DateTimeField(auto_now=True)),
                ('cod_park', models.CharField(max_length=255, unique=True)),
                ('num_wtg', models.IntegerField()),
                ('id_complexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parque', to='ativos.complexo')),
            ],
            options={
                'verbose_name': 'Parque',
                'verbose_name_plural': 'Parques',
                'db_table': 'parl_table',
            },
        ),
        migrations.CreateModel(
            name='Turbina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado_em', models.DateTimeField(auto_created=True)),
                ('atualizaocao', models.DateTimeField(auto_now=True)),
                ('condicao', models.CharField(max_length=255)),
                ('wtg_id', models.CharField(max_length=255, unique=True)),
                ('pk_intalado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turbina', to='ativos.parque')),
            ],
            options={
                'verbose_name': 'Turbina',
                'verbose_name_plural': 'Turbinas',
                'db_table': 'wtg_table',
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado_em', models.DateTimeField(auto_created=True)),
                ('atualizaocao', models.DateTimeField(auto_now=True)),
                ('pro_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('prop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usu_table',
                'unique_together': {('email', 'prop_id')},
            },
        ),
        migrations.AddField(
            model_name='complexo',
            name='propri_f_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexo', to='ativos.proprietario'),
        ),
    ]
